---
- name: Install nginx
  pkgng:
    name: nginx
    state: present
    cached: yes
  tags:
    - nginx

- name: Create log directory
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  tags:
    - nginx

- name: Configure RC service
  copy:
    content: "nginx_enable=\"YES\""
    dest: "{{ rc_conf_dir }}/nginx"
    owner: root
    group: wheel
    mode: '0644'
  tags:
    - nginx

- name: Write site configuration
  template:
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart nginx
  when: nginx_conf_src
  tags:
    - nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: running
  tags:
    - nginx
