---
- name: Install Ruby
  pkgng: name=ruby state=present

- name: Install riemann-dash gem
  gem: name=riemann-dash state=latest

- name: Enable riemann-dash RC
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: ^riemann_dash_enable=
    line: riemann_dash_enable="YES"

- name: Write rc configuration
  template:
    src: rc.dash.conf.j2
    dest: "{{ rc_conf_dir }}/riemann-dash.conf"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann-dash

- name: Write riemann-dash configuration
  template:
    src: riemann.config.j2
    dest: "{{ riemann_conf_dir }}/{{ riemann_dash_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann-dash

- name: Start Riemann dashboard
  service: name=riemann-dash state=running
