---
- name: Install Ruby
  pkgng:
    name: ruby
    state: present
    cached: yes

- name: Install riemann-dash gem
  gem:
    name: riemann-dash
    state: latest

- name: Enable riemann-dash service
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: ^riemann_dash_enable=
    line: riemann_dash_enable="YES"

- name: Set dashboard config path
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: ^riemann_dash_config=
    line: "riemann_dash_config=\"{{ riemann_conf_dir }}/{{ riemann_dash_conf_file }}\""
  notify:
    - restart riemann-dash

- name: Write dashboard configuration
  template:
    src: dash-config.rb.j2
    dest: "{{ riemann_conf_dir }}/{{ riemann_dash_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann-dash

- name: Start Riemann dashboard
  service:
    name: riemann-dash
    state: running
