---
- name: Install Java
  pkgng: name=openjdk8 state=present

- name: Install Riemann
  pkgng: name=riemann state=present

- name: Write rc configuration
  template:
    src: rc.riemann.conf.j2
    dest: "{{ rc_conf_dir }}/riemann.conf"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann

- name: Write Riemann configuration
  template:
    src: riemann.config.j2
    dest: "{{ riemann_conf_dir }}/{{ riemann_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload riemann

- name: Start Riemann service
  service: name=riemann state=running
