---
- name: Install Java
  pkgng:
    name: openjdk8
    state: present
    cached: yes

- name: Install Riemann
  pkgng:
    name: riemann
    state: present
    cached: yes

- name: Enable riemann service
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: ^riemann_enable=
    line: riemann_enable="YES"

- name: Set config path
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: ^riemann_config=
    line: "riemann_config=\"{{ riemann_conf_dir }}/{{ riemann_conf_file }}\""
  notify:
    - restart riemann

- name: Write Riemann configuration
  template:
    src: riemann.config.j2
    dest: "{{ riemann_conf_dir }}/{{ riemann_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload riemann

- name: Generate pkcs8 key
  shell: "openssl pkcs8 -topk8 -nocrypt -in /etc/ssl/private/{{ ansible_fqdn }}.key -out {{ riemann_conf_dir }}/tls-key.pkcs8"
  # TODO: only when input is newer than output
  notify:
    - restart riemann

- name: Start Riemann service
  service:
    name: riemann
    state: running
