---
- name: Install packages
  pkgng:
    name: "{{ item }}"
    state: present
    cached: yes
  with_items:
    - openjdk8
    - riemann
    - py27-pexpect-3.3

- name: Configure RC service
  template:
    src: rc.riemann.j2
    dest: "{{ rc_conf_dir }}/riemann"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann

- name: Write Riemann configuration
  template:
    src: riemann.config.j2
    dest: "{{ riemann_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    # TODO: ideally, should reload instead
    - restart riemann

- block:
    - name: Check PKCS8 key
      stat:
        path: "{{ riemann_tls_key }}"
      register: pkcs8_key
    - name: Generate pkcs8 key
      shell: "openssl pkcs8 -topk8 -nocrypt -in {{ tls_key_path }} -out {{ riemann_tls_key }}"
      when: not pkcs8_key.stat.exists or server_key.changed
      notify:
        - restart riemann

- block:
    - name: Clean trust store
      file:
        path: "{{ riemann_trust_store }}"
        state: absent
      when: root_ca.changed
    - name: Import Root CA into trust store
      expect:
        command: "keytool -import -file {{ tls_root_ca_path }} -alias myCA -keystore {{ riemann_trust_store }}"
        creates: "{{ riemann_trust_store }}"
        responses:
          "Enter keystore password": "abcdef"
          "Re-enter new password": "abcdef"
          "Trust this certificate": "yes"
      notify:
        - restart riemann

- name: Start Riemann service
  service:
    name: riemann
    state: running
