---
- name: Install Java
  pkgng:
    name: openjdk8
    state: present
    cached: yes

- name: Install Riemann
  pkgng:
    name: riemann
    state: present
    cached: yes

- name: Configure RC service
  template:
    src: rc.riemann.j2
    dest: "{{ rc_conf_dir }}/riemann"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann

- name: Write Riemann configuration
  template:
    src: riemann.config.j2
    dest: "{{ riemann_conf_dir }}/{{ riemann_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload riemann

- name: Generate pkcs8 key
  shell: "openssl pkcs8 -topk8 -nocrypt -in /etc/ssl/private/{{ ansible_fqdn }}.key -out {{ riemann_conf_dir }}/tls-key.pkcs8"
  # TODO: only when input is newer than output
  notify:
    - restart riemann

- name: Start Riemann service
  service:
    name: riemann
    state: running
