---
- name: Install Ruby
  pkgng:
    name: ruby
    state: present
    cached: yes

- name: Install riemann-dash gem
  gem:
    name: riemann-dash
    state: latest

- name: Configure RC service
  template:
    src: rc.dash.j2
    dest: "{{ rc_conf_dir }}/riemann-dash"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann-dash

- name: Write dashboard configuration
  template:
    src: dash-config.rb.j2
    dest: "{{ riemann_conf_dir }}/{{ riemann_dash_conf_file }}"
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart riemann-dash

- name: Ensure riemann-dash is running
  service:
    name: riemann-dash
    state: running
