---
- name: Install InfluxDB
  pkgng:
    name: influxdb
    state: present
    cached: yes
  tags:
    - influxdb

- name: Enable influxd service
  copy:
    content: "influxd_enable=\"YES\""
    dest: "{{ rc_conf_dir }}/influxd"
    owner: root
    group: wheel
    mode: '0644'
  tags:
    - influxdb

- name: Prepare data directory
  file:
    path: "{{ influxdb_data_dir }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    mode: '0755'
  tags:
    - influxdb

- name: Write InfluxDB configuration
  template:
    src: influxd.conf.j2
    dest: /usr/local/etc/influxd.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart influxd
  tags:
    - influxdb

- name: Ensure influxd is running
  service:
    name: influxd
    state: running
  tags:
    - influxdb
