---
- name: Install InfluxDB
  pkgng:
    name: influxdb
    state: present
    cached: yes

- name: Enable influxd service
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: ^influxd_enable=
    line: influxd_enable="YES"

- name: Prepare data directory
  file:
    path: "{{ influxdb_data_dir }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    mode: '0755'

- name: Write InfluxDB configuration
  template:
    src: influxd.conf.j2
    dest: /usr/local/etc/influxd.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart influxd

- name: Run InfluxDB service
  service:
    name: influxd
    state: running
