---
- name: Install Grafana
  pkgng:
    name: grafana2
    state: present
    cached: yes
  tags:
    - grafana

- name: Configure RC service
  copy:
    content: "grafana2_enable=\"YES\""
    dest: "{{ rc_conf_dir }}/grafana2"
    owner: root
    group: wheel
    mode: '0644'
  tags:
    - grafana

- name: Write Grafana configuration
  template:
    src: grafana2.conf.j2
    dest: /usr/local/etc/grafana2.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart grafana
  tags:
    - grafana

- name: Ensure Grafana is running
  service:
    name: grafana2
    state: running
  tags:
    - grafana
