---
- hosts: riemann
  remote_user: admin
  become: true
  roles:
    - tls-cert
    - riemann

- hosts: influxdb
  remote_user: admin
  become: true
  roles:
    - tls-cert
    - influxdb

- hosts: grafana
  remote_user: admin
  become: true
  roles:
    - tls-cert
    - grafana
