---
- hosts: riemann
  remote_user: admin
  become: true
  vars_files:
    - private/vars.yml
  roles:
    - riemann

- hosts: influxdb
  remote_user: admin
  become: true
  vars_files:
    - private/vars.yml
  roles:
    - influxdb

- hosts: grafana
  remote_user: admin
  become: true
  vars_files:
    - private/vars.yml
  roles:
    - grafana
