---
tls_root_ca_path: "{{ tls_certs_dir }}/{{ tls_root_ca }}.crt"
tls_intermediate_ca_path: "{{ tls_certs_dir }}/{{ tls_intermediate_ca }}.crt"
tls_cert_path: "{{ tls_certs_dir }}/{{ tls_cert_name }}.crt"
tls_chained_cert_path: "{{ tls_certs_dir }}/chained_{{ tls_cert_name }}.crt"
