---
rc_conf_dir: /etc/rc.conf.d

# Riemann settings
riemann_enable: yes
riemann_conf_dir: /usr/local/etc/riemann

riemann_metrics_bind: 0.0.0.0
riemann_tls_port: 5554
riemann_tcp_port: 5555
riemann_udp_port: 5555

riemann_ws_bind: 127.0.0.1
riemann_ws_port: 5556
riemann_ws_port_internal: 5557

# Dashboard settings
riemann_dash_enable: yes
riemann_dash_conf_file: dash-config.rb
riemann_dash_bind_address: 127.0.0.1
riemann_dash_port: 5558
